[programs:invest]
comand=/home/dony/venv/bin/gunicorn Investsite.config.wsgi:application -c /home/dony/invest-search/config/gunicorn.conf.py
directory=/home/dony/invest-search
user = dony
autorestart=true
redirect_stderr=true
stdout_logfile= /home/dony/invest-search/logs/debug.log