# Generated by Django 4.1.dev20211213070928 on 2022-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0005_commerce_energy_it_placeofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='category',
        ),
        migrations.AddField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('energy', 'energy'), ('commerce', 'commerce'), ('production', 'production'), ('it', 'it'), ('placeofbirth', 'placeofbirth')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
