# Generated by Django 4.1.dev20211213070928 on 2022-06-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0006_remove_addproject_category_addproject_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='commerce',
        ),
        migrations.DeleteModel(
            name='energy',
        ),
        migrations.DeleteModel(
            name='IT',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PlaceOfBirth',
        ),
        migrations.AddField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('placeofbirth', 'placeofbirth'), ('commerce', 'commerce'), ('it', 'it'), ('energy', 'energy'), ('production', 'production')], max_length=20),
        ),
    ]
