# Generated by Django 4.1.dev20211213070928 on 2022-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0007_delete_category_delete_commerce_delete_energy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='regions',
        ),
        migrations.AddField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('jalal-abad', 'jalal-abad'), ('chuy', 'chuy'), ('naryn', 'naryn'), ('osh', 'osh'), ('batken', 'batken'), ('tealas', 'tealas')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('it', 'it'), ('energy', 'energy'), ('placeofbirth', 'placeofbirth'), ('production', 'production'), ('commerce', 'commerce')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
