# Generated by Django 4.1.dev20211213070928 on 2022-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0008_remove_addproject_regions_addproject_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('energy', 'energy'), ('production', 'production'), ('commerce', 'commerce'), ('placeofbirth', 'placeofbirth'), ('it', 'it')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('chuy', 'chuy'), ('talas', 'talas'), ('batken', 'batken'), ('osh', 'osh'), ('naryn', 'naryn'), ('jalal-abad', 'jalal-abad')], max_length=20),
        ),
    ]
