# Generated by Django 4.0.4 on 2022-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0010_form_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('energy', 'energy'), ('placeofbirth', 'placeofbirth'), ('production', 'production'), ('it', 'it')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Naryn', 'Naryn'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Osh', 'Osh'), ('Batken', 'Batken')], max_length=20),
        ),
    ]
