# Generated by Django 4.0.4 on 2022-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0011_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('placeofbirth', 'placeofbirth'), ('production', 'production'), ('it', 'it'), ('energy', 'energy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Issyk-kul', 'Issyk-kul'), ('Batken', 'Batken'), ('Naryn', 'Naryn'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
