# Generated by Django 4.0.4 on 2022-07-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0012_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('placeofbirth', 'placeofbirth'), ('it', 'it'), ('energy', 'energy'), ('commerce', 'commerce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Naryn', 'Naryn'), ('Chuy', 'Chuy'), ('Talas', 'Talas'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Batken', 'Batken'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
