# Generated by Django 4.0.4 on 2022-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0017_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('it', 'it'), ('placeofbirth', 'placeofbirth'), ('commerce', 'commerce'), ('energy', 'energy'), ('production', 'production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Naryn', 'Naryn'), ('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Osh', 'Osh'), ('Batken', 'Batken'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul')], max_length=20),
        ),
    ]
