# Generated by Django 4.0.4 on 2022-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0019_delete_post_alter_addproject_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('energy', 'energy'), ('it', 'it'), ('placeofbirth', 'placeofbirth'), ('production', 'production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Naryn', 'Naryn'), ('Batken', 'Batken'), ('Chuy', 'Chuy'), ('Talas', 'Talas'), ('Issyk-kul', 'Issyk-kul'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
