# Generated by Django 4.0.4 on 2022-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0021_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('placeofbirth', 'placeofbirth'), ('production', 'production'), ('it', 'it'), ('energy', 'energy'), ('commerce', 'commerce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Osh', 'Osh'), ('Chuy', 'Chuy'), ('Issyk-kul', 'Issyk-kul'), ('Batken', 'Batken'), ('Talas', 'Talas'), ('Jalal-abad', 'Jalal-abad'), ('Naryn', 'Naryn')], max_length=20),
        ),
    ]
