# Generated by Django 4.0.4 on 2022-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0022_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('production', 'production'), ('it', 'it'), ('energy', 'energy'), ('placeofbirth', 'placeofbirth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Chuy', 'Chuy'), ('Jalal-abad', 'Jalal-abad'), ('Osh', 'Osh'), ('Batken', 'Batken'), ('Issyk-kul', 'Issyk-kul'), ('Naryn', 'Naryn'), ('Talas', 'Talas')], max_length=20),
        ),
    ]
