# Generated by Django 4.0.4 on 2022-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0023_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('it', 'it'), ('placeofbirth', 'placeofbirth'), ('production', 'production'), ('commerce', 'commerce'), ('energy', 'energy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Issyk-kul', 'Issyk-kul'), ('Talas', 'Talas'), ('Batken', 'Batken'), ('Naryn', 'Naryn'), ('Osh', 'Osh'), ('Chuy', 'Chuy'), ('Jalal-abad', 'Jalal-abad')], max_length=20),
        ),
    ]
