# Generated by Django 4.0.4 on 2022-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0025_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('energy', 'energy'), ('placeofbirth', 'placeofbirth'), ('commerce', 'commerce'), ('production', 'production'), ('it', 'it')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Osh', 'Osh'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Chuy', 'Chuy'), ('Issyk-kul', 'Issyk-kul'), ('Batken', 'Batken')], max_length=20),
        ),
    ]
