# Generated by Django 4.0.4 on 2022-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0026_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Osh', 'Osh'), ('Naryn', 'Naryn'), ('Talas', 'Talas'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Batken', 'Batken'), ('Chuy', 'Chuy')], max_length=20),
        ),
    ]
