# Generated by Django 4.0.4 on 2022-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0028_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('production', 'production'), ('it', 'it'), ('energy', 'energy'), ('placeofbirth', 'placeofbirth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Osh', 'Osh'), ('Issyk-kul', 'Issyk-kul'), ('Talas', 'Talas'), ('Batken', 'Batken'), ('Jalal-abad', 'Jalal-abad'), ('Naryn', 'Naryn'), ('Chuy', 'Chuy')], max_length=20),
        ),
    ]
