# Generated by Django 4.0.4 on 2022-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0029_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('placeofbirth', 'placeofbirth'), ('it', 'it'), ('energy', 'energy'), ('production', 'production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Batken', 'Batken'), ('Naryn', 'Naryn'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
