# Generated by Django 4.0.4 on 2022-07-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0030_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('energy', 'energy'), ('it', 'it'), ('commerce', 'commerce'), ('placeofbirth', 'placeofbirth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Batken', 'Batken'), ('Issyk-kul', 'Issyk-kul'), ('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Osh', 'Osh'), ('Jalal-abad', 'Jalal-abad'), ('Naryn', 'Naryn')], max_length=20),
        ),
    ]
