# Generated by Django 4.0.4 on 2022-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0031_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('placeofbirth', 'placeofbirth'), ('commerce', 'commerce'), ('energy', 'energy'), ('it', 'it')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Batken', 'Batken'), ('Jalal-abad', 'Jalal-abad'), ('Naryn', 'Naryn'), ('Chuy', 'Chuy'), ('Osh', 'Osh'), ('Issyk-kul', 'Issyk-kul'), ('Talas', 'Talas')], max_length=20),
        ),
    ]
