# Generated by Django 4.0.4 on 2022-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0032_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('it', 'it'), ('production', 'production'), ('energy', 'energy'), ('commerce', 'commerce'), ('placeofbirth', 'placeofbirth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Naryn', 'Naryn'), ('Osh', 'Osh'), ('Chuy', 'Chuy'), ('Batken', 'Batken'), ('Talas', 'Talas')], max_length=20),
        ),
    ]
