# Generated by Django 4.0.4 on 2022-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0034_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('placeofbirth', 'placeofbirth'), ('it', 'it'), ('energy', 'energy'), ('commerce', 'commerce'), ('production', 'production')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Batken', 'Batken'), ('Jalal-abad', 'Jalal-abad'), ('Chuy', 'Chuy'), ('Issyk-kul', 'Issyk-kul'), ('Naryn', 'Naryn'), ('Talas', 'Talas'), ('Osh', 'Osh')], max_length=20),
        ),
    ]
