# Generated by Django 4.0.4 on 2022-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0036_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('commerce', 'commerce'), ('placeofbirth', 'placeofbirth'), ('energy', 'energy'), ('production', 'production'), ('it', 'it')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Batken', 'Batken'), ('Chuy', 'Chuy'), ('Jalal-abad', 'Jalal-abad'), ('Talas', 'Talas'), ('Issyk-kul', 'Issyk-kul'), ('Osh', 'Osh'), ('Naryn', 'Naryn')], max_length=20),
        ),
    ]
