# Generated by Django 4.0.4 on 2022-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0037_alter_addproject_group_alter_addproject_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('it', 'it'), ('placeofbirth', 'placeofbirth'), ('commerce', 'commerce'), ('energy', 'energy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Batken', 'Batken'), ('Osh', 'Osh'), ('Issyk-kul', 'Issyk-kul'), ('Chuy', 'Chuy')], max_length=20),
        ),
    ]
