# Generated by Django 4.0.4 on 2022-07-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0039_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('production', 'production'), ('placeofbirth', 'placeofbirth'), ('energy', 'energy'), ('it', 'it'), ('commerce', 'commerce')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Jalal-abad', 'Jalal-abad'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Issyk-kul', 'Issyk-kul'), ('Chuy', 'Chuy'), ('Osh', 'Osh'), ('Batken', 'Batken')], max_length=20),
        ),
    ]
