# Generated by Django 4.0.4 on 2022-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0040_alter_addproject_group_alter_addproject_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='group',
            field=models.CharField(choices=[('energy', 'energy'), ('production', 'production'), ('commerce', 'commerce'), ('it', 'it'), ('placeofbirth', 'placeofbirth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='region',
            field=models.CharField(choices=[('Osh', 'Osh'), ('Batken', 'Batken'), ('Talas', 'Talas'), ('Chuy', 'Chuy'), ('Jalal-abad', 'Jalal-abad'), ('Issyk-kul', 'Issyk-kul'), ('Naryn', 'Naryn')], max_length=20),
        ),
    ]
